version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: bizerp_postgres
    environment:
      POSTGRES_USER: bizerp
      POSTGRES_PASSWORD: bizerp
      POSTGRES_DB: bizerp
    ports:
      - '5432:5432'
    volumes:
      - bizerp_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U bizerp -d bizerp']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  bizerp_pgdata:
